### ISSUE TITLE
daisy // pie-caf // Failed to load WiFi driver

### ISSUE THREAD

**Issue by eremitein** [Genom-Projek/android_kernel_xiaomi_msm8953#2]
hello!
please, help me

device Xiaomi Mi A2 Lite daisy

kernel compiled with this config which based on daisy-perf_defconfig 
[config.txt](https://github.com/rama982/android_kernel_xiaomi_msm8953/files/2855471/config.txt)

this is kernel build logs, all clean 
[kernel.log.txt](https://github.com/rama982/android_kernel_xiaomi_msm8953/files/2855477/kernel.log.txt)

Image.gz was installed and booted okey. but wifi don't working((
 
logcat:

02-12 16:17:44.538  1539  1746 E HalDevMgr: createStaIface: Starting wifi
02-12 16:17:44.540  1539  1746 E HalDevMgr: createStaIface: Creating iface
02-12 16:17:44.556   774   774 E android.hardware.wifi@1.0-service: finit_module return: -1: Required key not available
02-12 16:17:44.556   774   774 E android.hardware.wifi@1.0-service: Failed to load WiFi driver
02-12 16:17:44.556  1539  1746 E HalDevMgr: executeChipReconfiguration: configureChip error: 9 ()
02-12 16:17:44.556  1539  1746 E WifiVendorHal: Failed to create STA iface
02-12 16:17:44.556  1539  1746 E WifiNative: Failed to create STA iface in vendor HAL
02-12 16:17:44.557  1539  1746 E WifiClientModeManager: Failed to create ClientInterface. Sit in Idle

**Comment by ramabondanp** [comment]
Is this for miui?

**Comment by eremitein** [comment]
no, daisy is an Android One phone. now installed GSI rom. with stock kernel wi-fi work, with builded kernel - nonono

are you mean what "pie-caf" branch not for this device?

**Comment by ramabondanp** [comment]
@eremitein You installing on stock rom, 
So you need to make wlan driver as module, sign it, and push to /vendor/lib/modules(/pronto/)
I have script for it, check my kernel_scripts repo and use sakura miui script.

**Comment by eremitein** [comment]
> @eremitein You installing on stock rom,
> So you need to make wlan driver as module, sign it, and push to /vendor/lib/modules(/pronto/)
> I have script for it, check my kernel_scripts repo and use sakura miui script.

hello!

i tried it. with signed pronto_wlan.ko module i get same errors

02-13 14:58:21.424   749   749 E android.hardware.wifi@1.0-service: finit_module return: -1: Required key not available
02-13 14:58:21.424   749   749 E android.hardware.wifi@1.0-service: Failed to load WiFi driver
02-13 14:58:21.424  1536  1714 D HalDevMgr: onChipReconfigureFailure: status=9 ()
02-13 14:58:21.424  1536  1727 E HalDevMgr: executeChipReconfiguration: configureChip error: 9 ()
02-13 14:58:21.424  1536  1727 E WifiVendorHal: Failed to create STA iface
02-13 14:58:21.424  1536  1727 E WifiNative: Failed to create STA iface in vendor HAL
02-13 14:58:21.424  1536  1727 E WifiClientModeManager: Failed to create ClientInterface. Sit in Idle
02-13 14:58:21.424  1536  1727 D WifiStateMachinePrime: State changed from client mode. state = 4
02-13 14:58:21.424  1536  1727 D WifiClientModeManager: expected stop, not triggering callbacks: newState = 1

**Comment by eremitein** [comment]
other modules load fine, i check it with "insmod" command

but pronto return me 

insmod: failed to load /vendor/lib/modules/pronto/pronto_wlan.ko: Required key not available

**Comment by eremitein** [comment]
@rama982 

i builded kernel and modules with your script with a few modification.

now i have a new error, signed pronto_wlan.ko return 
                                                  
02-13 18:34:11.001   759   759 E android.hardware.wifi@1.0-service: finit_module return: -1: Exec format error            
02-13 18:34:11.001   759   759 E android.hardware.wifi@1.0-service: Failed to load WiFi driver

**Comment by ramabondanp** [comment]
@eremitein Can you push your kernel source and script? Maybe there some missing thing. Only log not help anything

**Comment by eremitein** [comment]
it's your kernel source, not patched
pure "pie-caf" branch

[daisy-miui.sh.txt](https://github.com/rama982/android_kernel_xiaomi_msm8953/files/2861032/daisy-miui.sh.txt)

[zero.config.txt](https://github.com/rama982/android_kernel_xiaomi_msm8953/files/2861137/zero.config.txt)

**Comment by eremitein** [comment]
additional issue found - for daisy don't autocreated folder AnyKernel2/modules/system/vendor/lib/modules

i created it manually

**Comment by eremitein** [comment]
in short problem with pronto module was:

- if built-in then no wifi anyway
- if using w/o sign then "Required key not available"
- if using signed then "Exec format error"

**Comment by ramabondanp** [comment]
i just build one, try this kernel
https://drive.google.com/file/d/1wgKTZBI6AIGZjPZ74YqVJtYc2E0dzENS/view?usp=sharing
and tell me the result

**Comment by eremitein** [comment]
> i just build one, try this kernel
> https://drive.google.com/file/d/1wgKTZBI6AIGZjPZ74YqVJtYc2E0dzENS/view?usp=sharing
> and tell me the result

awesome!! wifi work!

how you did it?
where is my mistake?

**Comment by ramabondanp** [comment]
> > i just build one, try this kernel
> > https://drive.google.com/file/d/1wgKTZBI6AIGZjPZ74YqVJtYc2E0dzENS/view?usp=sharing
> > and tell me the result
> 
> awesome!! wifi work!
> 
> how you did it?
> where is my mistake?

There is some derp on my script, but it fixed now.
check my kernel_scripts repo and use daisy-stock.sh

But first change 
`CONFIG_PRONTO_WLAN=y`
on defconfig to
`CONFIG_PRONTO_WLAN=m`

**Comment by eremitein** [comment]
@rama982 big THANKS for you!

i'll try compile kernel tomorrow when have access to my build environment

**Comment by eremitein** [comment]
all worked!!! thanks again!

and i found collision - if disable "Size Optimization" in kernel config (CONFIG_CC_OPTIMIZE_FOR_SIZE),
then signed pronto module not loaded due "Exec format error"

**Comment by MightyM17** [comment]
Hello, sorry for reopening this issue, but im facing the same issue of `android.hardware.wifi@1.0-service: Failed to load WiFi driver` (but for other device not daisy) could you tell what did you do and where the module is placed?

**Comment by goldfish07** [comment]
@MightyM17 use stock android.hardware.wifi@1.0-service

**Comment by MightyM17** [comment]
Fixed it, it was a kernel issue

**Comment by UDPSendToFailed** [comment]
May I ask how you guys solved this? Having the same problem with msm8953 on gta2xlwifi, setting `CONFIG_PRONTO_WLAN=m` and enabling `CONFIG_CC_OPTIMIZE_FOR_SIZE` in kernel defconfig has no effect. Using android.hardware.wifi@1.0-service from stock vendor didn't help either.

```
E android.hardware.wifi@1.0-service: finit_module return: -1: Exec format error
E android.hardware.wifi@1.0-service: Failed to load WiFi driver
E android.hardware.wifi@1.0-service: Failed to initialize firmware mode controller
E android.hardware.wifi@1.0-service: Wifi HAL start failed
E HalDevMgr: Cannot start IWifi: 9 ()
E WifiVendorHal: Failed to start vendor HAL
E WifiNative: Failed to start vendor HAL
E WifiNative: Failed to start Hal
E WifiClientModeManager[unknown]: Failed to create ClientInterface. Sit in Idle
E WifiActiveModeWarden: ClientModeManager start failed!ConcreteClientModeManager{id=57357 iface=null role=null}
