### ISSUE TITLE
Redmi6 pro

### ISSUE THREAD

**Issue by Feardarks** [Genom-Projek/android_kernel_xiaomi_msm8953#3]
Hi mr dev.
Sorry for asking eta 
But can you update your kernel ? İ seen your kernel i tryed on older miui bulds, it was very good and smooth . Your's kernel is only one kernel is miui supported. Pls come back update your kernels...

**Comment by ramabondanp** [comment]
sakura user for my kernel is too little

**Comment by Feardarks** [comment]
sakura kernel users is mostly switch their roms to aosp for using custom kernels, we had to do... im miui lover but like other users i had to switch aosp roms...  İf can you update your kernel I'm sure it's would be popular kernel. bcz only your kernel is supporting miui :((((
