### ISSUE TITLE
Wifi does not work

### ISSUE THREAD

**Issue by cnjhb** [Genom-Projek/android_kernel_xiaomi_msm8953#5]
The size of wlan.ko is 60m. And could not be loaded.

**Comment by ramabondanp** [comment]
> The size of wlan.ko is 60m. And could not be loaded.

You need to strip the module and sign it

**Comment by cnjhb** [comment]
Sorry, I just forgot to put the module in / lib / modules

**Comment by cnjhb** [comment]
> > The size of wlan.ko is 60m. And could not be loaded.
> 
> You need to strip the module and sign it

Brother, why wlan.ko is so big.
